# Generated by Django 5.1.6 on 2025-04-03 23:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreignpostlike',
            name='foreign_authors',
        ),
        migrations.RemoveField(
            model_name='foreignpostlike',
            name='foreign_post',
        ),
        migrations.CreateModel(
            name='ForeignComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('global_id', models.URLField(unique=True)),
                ('comment', models.TextField()),
                ('content_type', models.CharField(default='text/plain', max_length=50)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('foreign_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_comments', to='authors.foreignauthor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_comments', to='authors.foreignpost')),
            ],
        ),
        migrations.DeleteModel(
            name='ForeignComments',
        ),
        migrations.DeleteModel(
            name='ForeignPostLike',
        ),
    ]
